pipeline {
    agent {
        docker { image 'cloudbees/jnlp-slave-with-java-build-tools' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
