version: '3'
services:
  tower:
    build:
      context: ./Tower
      dockerfile: Dockerfile-tower
    ports:
      - "443:443"
    environment:
      SERVER_NAME: localhost

  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    links:
      - "tower"
    volumes:
      - "./Jenkins/jenkins_home:/var/jenkins_home"

  gitlab:
    build:
      context: ./GitLab
      dockerfile: Dockerfile-gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:9090'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['gitlab_email_enabled'] = false
        gitlab_rails['initial_root_password'] = "password"
    ports:
      - '9090:9090'
      - '2224:22'
    volumes:
      - './GitLab//srv/gitlab/config:/etc/gitlab'
      - './GitLab//srv/gitlab/logs:/var/log/gitlab'
      - './GitLab/srv/gitlab/data:/var/opt/gitlab'
