version: '3'
services:
  #nexus:
    #image: sonatype/nexus3
    #volumes:
    #  - "./nexus/nexus-data:/nexus-data"
    #ports:
    #  - "8081:8081"
  
  tower:
    build:
      context: ./Tower
      dockerfile: Dockerfile-tower
    container_name: tower
    ports:
      - "443:443"
    environment:
      SERVER_NAME: localhost

  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile-jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    links:
      - "tower"
    volumes:
      - "./Jenkins/jenkins_home:/var/jenkins_home"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
  gitlab:
    build:
      context: ./GitLab
      dockerfile: Dockerfile-gitlab
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:9090'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['gitlab_email_enabled'] = false
        gitlab_rails['initial_root_password'] = "password"
    ports:
      - '9090:9090'
      - '2224:22'
    volumes:
      - './GitLab/srv/gitlab/config:/etc/gitlab'
      - './GitLab/srv/gitlab/logs:/var/log/gitlab'
      - './GitLab/srv/gitlab/data:/var/opt/gitlab'

  #elasticsearch:
  #  build:
  #    context: ./ES
  #    dockerfile: Dockerfile-elasticsearch
  #  container_name: elasticsearch
  #  environment:
  #    - cluster.name=docker-cluster
  #    - bootstrap.memory_lock=true
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #  ulimits:
  #    memlock:
  #      soft: -1
  #      hard: -1
    # volumes:
    #  - ./ES/data1:/usr/share/elasticsearch/data
  #  ports:
  #    - 9200:9200

  #elasticsearch2:
  #  build:
  #    context: ./ES
  #    dockerfile: Dockerfile-elasticsearch
  #  container_name: elasticsearch2
  #  environment:
  #    - cluster.name=docker-cluster
  #    - bootstrap.memory_lock=true
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #  ulimits:
  #    memlock:
  #      soft: -1
  #      hard: -1
  #  # volumes:
  #  #  - ./ES/data2:/usr/share/elasticsearch/data
