FROM jenkins/jenkins:lts

USER root

## Install tower-cli
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install python-pip
RUN pip install ansible-tower-cli

# So we can run the hosts docker in the container. 
RUN apt-get install -y libltdl7

# So we can run Jenkins configuration as code. 
RUN apt-get install -y maven

## Set up tower-cli config
RUN mkdir /etc/tower
RUN tower-cli config --scope global host tower
RUN tower-cli config --scope global username admin
RUN tower-cli config --scope global password password

# Install plugins
COPY setup-jenkins/plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# Set up ENV for Jenkins configuratin as code. 
RUN mkdir -p /usr/share/jenkins/casc_configs
ENV CASC_JENKINS_CONFIG="/usr/share/jenkins/casc_configs"
COPY setup-jenkins/casc_configs/jenkins.yml      /usr/share/jenkins/casc_configs/0-jenkins.yml
COPY setup-jenkins/casc_configs/gitlab.yml       /usr/share/jenkins/casc_configs/1-gitlab.yml
COPY setup-jenkins/casc_configs/credentials.yml  /usr/share/jenkins/casc_configs/2-credentials.yml

# Fix admin user
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
COPY setup-jenkins/security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy
