FROM jenkins/jenkins:lts

USER root

## Install tower-cli
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install python-pip
RUN pip install ansible-tower-cli

## Set up tower-cli config
RUN mkdir /etc/tower
RUN tower-cli config --scope global host tower
RUN tower-cli config --scope global username admin
RUN tower-cli config --scope global password password


# Fix admin user
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy

# Install plugins 
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
