FROM jenkins/jenkins:lts

USER root

## Install tower-cli
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install python-pip
RUN pip install ansible-tower-cli

## Set up tower-cli config
RUN tower-cli config --scope global host tower
RUN tower-cli config --scope global username admin
RUN tower-cli config --scope global password password
